blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/damon-houk/aws-multi-account-bootstrap/tree/main/docs
    about: Check our documentation for guides and troubleshooting
  - name: Discussions
    url: https://github.com/damon-houk/aws-multi-account-bootstrap/discussions
    about: Ask questions and discuss with the community